# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SvamitvaPropertyCardGenerator
                                 A QGIS plugin
 Generates Property Card (PPM) for all parcels in the village 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-11
        copyright            : (C) 2025 by Pramod Kumar (Village Surveyor)
        email                : bpramod29@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SvamitvaPropertyCardGenerator class from file SvamitvaPropertyCardGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SVAMITVA_Property_Card_Generator import SvamitvaPropertyCardGenerator
    return SvamitvaPropertyCardGenerator(iface)
